### ISSUE TITLE
Recursion error running tests with master

### ISSUE THREAD

**Issue by takluyver** [jupyter-widgets/ipywidgets#1423]
[Failing test on Jenkins](https://jenkins.jupyter.org/job/traitlets-master-downstream-stable/82/consoleFull)

Summary of the failure:

```
======================================================================
ERROR: ipywidgets.widgets.tests.test_interaction.test_state_schema
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/jenkins/shiningpanda/jobs/65e9266d/virtualenvs/d41d8cd9/lib/python3.5/site-packages/traitlets/traitlets.py", line 490, in get
    value = obj._trait_values[self.name]
KeyError: 'min'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/jenkins/shiningpanda/jobs/65e9266d/virtualenvs/d41d8cd9/lib/python3.5/site-packages/traitlets/traitlets.py", line 490, in get
    value = obj._trait_values[self.name]
KeyError: 'max'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/jenkins/shiningpanda/jobs/65e9266d/virtualenvs/d41d8cd9/lib/python3.5/site-packages/traitlets/traitlets.py", line 490, in get
    value = obj._trait_values[self.name]
KeyError: 'min'

...
  File "/var/lib/jenkins/shiningpanda/jobs/65e9266d/virtualenvs/d41d8cd9/lib/python3.5/site-packages/traitlets/traitlets.py", line 562, in _validate
    value = self._cross_validate(obj, value)
  File "/var/lib/jenkins/shiningpanda/jobs/65e9266d/virtualenvs/d41d8cd9/lib/python3.5/site-packages/traitlets/traitlets.py", line 568, in _cross_validate
    value = obj._trait_validators[self.name](obj, proposal)
  File "/var/lib/jenkins/shiningpanda/jobs/65e9266d/virtualenvs/d41d8cd9/lib/python3.5/site-packages/traitlets/traitlets.py", line 928, in __call__
    return self.func(*args, **kwargs)
  File "/var/lib/jenkins/shiningpanda/jobs/65e9266d/virtualenvs/d41d8cd9/lib/python3.5/site-packages/ipywidgets/widgets/widget_int.py", line 113, in _validate_min
    if min > self.max:
  File "/var/lib/jenkins/shiningpanda/jobs/65e9266d/virtualenvs/d41d8cd9/lib/python3.5/site-packages/traitlets/traitlets.py", line 525, in __get__
    return self.get(obj, cls)
  File "/var/lib/jenkins/shiningpanda/jobs/65e9266d/virtualenvs/d41d8cd9/lib/python3.5/site-packages/traitlets/traitlets.py", line 498, in get
    value = self._validate(obj, default)
  File "/var/lib/jenkins/shiningpanda/jobs/65e9266d/virtualenvs/d41d8cd9/lib/python3.5/site-packages/traitlets/traitlets.py", line 562, in _validate
    value = self._cross_validate(obj, value)
  File "/var/lib/jenkins/shiningpanda/jobs/65e9266d/virtualenvs/d41d8cd9/lib/python3.5/site-packages/traitlets/traitlets.py", line 568, in _cross_validate
    value = obj._trait_validators[self.name](obj, proposal)
RecursionError: maximum recursion depth exceeded

----------------------------------------------------------------------
Ran 54 tests in 1.074s
```

**Comment by rmorshea** [comment]
@takluyver see https://github.com/jupyter-widgets/ipywidgets/pull/1409

**Comment by takluyver** [comment]
Aha,  thanks.

**Comment by takluyver** [comment]
I suspect that https://github.com/ipython/traitlets/issues/363 also refers to the same problem, though it's light on detail.

**Comment by rmorshea** [comment]
@takluyver, yup.

**Comment by jasongrout** [comment]
@rmorshea - is this a duplicate? Should we close it?

**Comment by jasongrout** [comment]
As noted in https://github.com/ipython/traitlets/pull/435, this should be fixed now.
