### ISSUE TITLE
conda install -c conda-forge ipywidgets --force not working

### ISSUE THREAD

**Issue by jmbertoncelli** [jupyter-widgets/ipywidgets#1740]
The following packages will be UPDATED:

    ipywidgets: 6.0.0-py27_0 --> 7.0.1-py_2 conda-forge

Proceed ([y]/n)? y

An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : linux-64
          conda version : 4.3.9
       conda is private : False
      conda-env version : 4.3.9
    conda-build version : 3.0.19
         python version : 2.7.13.final.0
       requests version : 2.14.2
       root environment : /root/miniconda2  (writable)
    default environment : /root/miniconda2/envs/snake27.10
       envs directories : /root/miniconda2/envs
          package cache : /root/miniconda2/pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /root/.condarc
           offline mode : False
             user-agent : conda/4.3.9 requests/2.14.2 CPython/2.7.13 Linux/3.10.0-693.2.2.el7.x86_64 CentOS Linux/7.4.1708 glibc/2.17
                UID:GID : 0:0

`$ /root/miniconda2/envs/snake27.10/bin/conda install -c conda-forge ipywidgets --force`

    Traceback (most recent call last):
      File "/root/miniconda2/lib/python2.7/site-packages/conda/exceptions.py", line 616, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/root/miniconda2/lib/python2.7/site-packages/conda/cli/main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "/root/miniconda2/lib/python2.7/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/root/miniconda2/lib/python2.7/site-packages/conda/cli/install.py", line 359, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "/root/miniconda2/lib/python2.7/site-packages/conda/plan.py", line 837, in execute_actions
        execute_instructions(plan, index, verbose)
      File "/root/miniconda2/lib/python2.7/site-packages/conda/instructions.py", line 258, in execute_instructions
        cmd(state, arg)
      File "/root/miniconda2/lib/python2.7/site-packages/conda/instructions.py", line 119, in UNLINKLINKTRANSACTION_CMD
        txn.execute()
      File "/root/miniconda2/lib/python2.7/site-packages/conda/core/link.py", line 256, in execute
        self.verify()
      File "/root/miniconda2/lib/python2.7/site-packages/conda/core/link.py", line 239, in verify
        self.prepare()
      File "/root/miniconda2/lib/python2.7/site-packages/conda/core/link.py", line 170, in prepare
        concatv(unlink_actions, link_actions))
      File "/root/miniconda2/lib/python2.7/site-packages/conda/core/link.py", line 169, in <genexpr>
        self.all_actions = tuple(per_pkg_actions for per_pkg_actions in
      File "/root/miniconda2/lib/python2.7/site-packages/conda/core/link.py", line 166, in <genexpr>
        for pkg_info, lt in zip(self.packages_info_to_link, link_types)
      File "/root/miniconda2/lib/python2.7/site-packages/conda/core/link.py", line 395, in make_link_actions
        python_entry_point_actions = CreatePythonEntryPointAction.create_actions(*required_quad)
      File "/root/miniconda2/lib/python2.7/site-packages/conda/core/path_actions.py", line 388, in create_actions
        for ep_def in noarch.entry_points)
      File "/root/miniconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 413, in __get__
        raise AttributeError("A value for {0} has not been set".format(self.name))
    AttributeError: A value for entry_points has not been set

**Comment by jasongrout** [comment]
This looks like possibly the same issue: https://github.com/conda/conda/issues/5941

Could you try updating conda and trying again? The comment above mentions conda 4.3.25, for example.

This comment (https://github.com/conda/conda/issues/4372#issuecomment-278328991) also seems to indicate that updating conda might fix the issue.

**Comment by jasongrout** [comment]
@jmbertoncelli - did updating conda fix the issue?

**Comment by jasongrout** [comment]
I'll close this as answered, but @jmbertoncelli - feel free to reopen if the above fix doesn't work.
