### ISSUE TITLE
Starting an ipykernel without widgets installed causes an error

### ISSUE THREAD

**Issue by jasongrout** [jupyter-widgets/ipywidgets#1901]
Because of the hardcoded hack in ipykernel, I'm getting an error when trying to start a python kernel without widgets installed:

```
Traceback (most recent call last):
  File "[snip]/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "[snip]/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "[snip]/lib/python3.6/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "[snip]/lib/python3.6/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-123>", line 2, in initialize
  File "[snip]/lib/python3.6/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "[snip]/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 463, in initialize
    self.init_extensions()
  File "[snip]/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 419, in init_extensions
    extension_man.load_extension('ipywidgets')
  File "[snip]/lib/python3.6/site-packages/IPython/core/extensions.py", line 86, in load_extension
    if mod.__file__.startswith(self.ipython_extension_dir):
AttributeError: module 'ipywidgets' has no attribute '__file__'
```
It seems that the init_extensions method has an except handler for an ImportError, but the AttributeError above slips through. Relevant lines are https://github.com/ipython/ipykernel/blob/3b6d0894aa77079da306a2de0ec5087c98de08f7/ipykernel/kernelapp.py#L414-L422

**Comment by aspiringguru** [comment]
also experiencing this error, not sure if exactly same issue.

my config.
$ ipython --version
6.2.1
$ jupyter --version
4.4.0

$ pip freeze | grep ipywidgets
ipywidgets==7.1.2

and testing inside the jupyter notebook code.
print (widgets.__version__)
7.1.2


$  python --version
Python 3.6.4 :: Anaconda, Inc.

I had just installed above on a fresh AWS instance of "Deep Learning AMI (Amazon Linux) Version 6.0 - ami-9c039de4". (not expecting this will be overly relevant)

was testing the examples here.
https://ipywidgets.readthedocs.io/en/latest/examples/Widget%20List.html

These worked.
widgets.IntSlider
widgets.FloatSlider 

this did not.
widgets.FloatLogSlider(
    value=10,
    base=10,
    min=-10, # max exponent of base
    max=10, # min exponent of base
    step=0.2, # exponent step
    description='Log Slider'
)
AttributeError                            Traceback (most recent call last)
<ipython-input-16-28f1ce065eb7> in <module>()
----> 1 widgets.FloatLogSlider(
      2     value=10,
      3     base=10,
      4     min=-10, # max exponent of base
      5     max=10, # min exponent of base

AttributeError: module 'ipywidgets' has no attribute 'FloatLogSlider'

not sure if I should raise as a new git issue. haven't tried downgrading to an earlier version of widgets yet.

**Comment by jasongrout** [comment]
FloatLogSlider is in ipywidgets 7.2, so please upgrade.

**Comment by vidartf** [comment]
Seen as well. Is there a corresponding issue for ipykernel?

**Comment by jasongrout** [comment]
I'm not sure. If not, I should have submitted one :(.

**Comment by jasongrout** [comment]
I think we can just take out the entire hack section - the effective thing that it does is to register the comm target, which we used to need right at kernel startup, but we don't need anymore. The only difference, I think, would be that frontends that are creating widgets in a new kernel would need to somehow import the library (thereby loading the extension and registering the kernel comm target) before trying to create a widget from the front end.
