### ISSUE TITLE
Building the documentation shows tornado error messages

### ISSUE THREAD

**Issue by SylvainCorlay** [jupyter-widgets/ipywidgets#2115]
```
ERROR:tornado.application:Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x103c4aea0>)
Traceback (most recent call last):
  File "/Users/scorlay/miniconda3/lib/python3.6/site-packages/tornado/ioloop.py", line 759, in _run_callback
    ret = callback()
  File "/Users/scorlay/miniconda3/lib/python3.6/site-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/Users/scorlay/miniconda3/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 263, in enter_eventloop
    self.eventloop(self)
  File "<ipython-input-1-e1e249360643>", line 18, in loop_asyncio
    loop.run_until_complete(loop.shutdown_asyncgens())
  File "/Users/scorlay/miniconda3/lib/python3.6/asyncio/base_events.py", line 455, in run_until_complete
    self.run_forever()
  File "/Users/scorlay/miniconda3/lib/python3.6/asyncio/base_events.py", line 409, in run_forever
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
```

**Comment by jasongrout** [comment]
Git bisect tracks it down to this commit: https://github.com/jupyter-widgets/ipywidgets/commit/a136dcd9846f8786f52bdc9ab90c52864a8d9da6

**Comment by jasongrout** [comment]
Looks like the asyncio loop code in the async notebook has a problem in it. If a loop is already running, it immediately falls through to trying to shutdown the loop. Instead, we should put the test for running outside the try/except. I'll submit a PR. We'll probably also need to fix this in ipykernel.

**Comment by jasongrout** [comment]
Actually, it looks like @minrk fixed all the problems with the asyncio event loop integration in ipykernel, so really we should just delete our example integration and say to use current ipykernel.

**Comment by jasongrout** [comment]
Related to #2112, which also is about deleting this example in the docs.
