### ISSUE TITLE
sliders not loading

### ISSUE THREAD

**Issue by norrisan** [jupyter-widgets/ipywidgets#2293]
I was using the interact feature without problems but sometime over the xmas period 
when I went back to use it , it somehow wasn't woking.

The only other work I did in the meantime was with TKinter

![image](https://user-images.githubusercontent.com/40805460/51247872-acffb380-198e-11e9-918b-03f096b1e2d9.png)

I am using anaconda and jupyter notebooks.

I have two environments:
base
and anaconda3

I have tried (I think correctly) updating everything, and folowed the suggestions in previous comments

![image](https://user-images.githubusercontent.com/40805460/51247976-fbad4d80-198e-11e9-9ba5-10d1fe578315.png)

![image](https://user-images.githubusercontent.com/40805460/51247991-07007900-198f-11e9-9fd4-1bb95522419e.png)

![image](https://user-images.githubusercontent.com/40805460/51248020-1da6d000-198f-11e9-96f9-11453690392e.png)

I'm loosing a lot of time, and am not a programmer by training. So any help would be greatly 
appreciated

**Comment by norrisan** [comment]
![image](https://user-images.githubusercontent.com/40805460/51248135-855d1b00-198f-11e9-81b5-ef809c1bca58.png)

versus

![image](https://user-images.githubusercontent.com/40805460/51248173-9dcd3580-198f-11e9-8746-8fdcdca7b3ae.png)

**Comment by norrisan** [comment]
[I 16:53:01.101 NotebookApp] JupyterLab extension loaded from C:\Users\The Dominator\Anaconda3\lib\site-packages\jupyterlab
[I 16:53:01.101 NotebookApp] JupyterLab application directory is C:\Users\The Dominator\Anaconda3\share\jupyter\lab
[I 16:53:01.102 NotebookApp] Serving notebooks from local directory: C:\Users\The Dominator
[I 16:53:01.102 NotebookApp] The Jupyter Notebook is running at:
[I 16:53:01.102 NotebookApp] http://localhost:8888/?token=2f647ae956754205d772425cd56dde3bed5c5a97dfa968b4
[I 16:53:01.102 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 16:53:01.150 NotebookApp] 

To access the notebook, open this file in a browser:
file:///C:/Users/The%20Dominator/AppData/Roaming/jupyter/runtime/nbserver-7156-open.html
Or copy and paste one of these URLs:
http://localhost:8888/?token=2f647ae956754205d772425cd56dde3bed5c5a97dfa968b4
[I 16:53:07.737 NotebookApp] Creating new notebook in 
[E 16:53:09.049 NotebookApp] Uncaught exception GET /api/config/notebook?_=1547653988936 (::1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/api/config/notebook?_=1547653988936', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
File "C:\Users\The Dominator\Anaconda3\lib\site-packages\tornado\web.py", line 1590, in _execute
result = method(*self.path_args, **self.path_kwargs)
File "C:\Users\The Dominator\Anaconda3\lib\site-packages\tornado\web.py", line 3006, in wrapper
return method(self, *args, **kwargs)
File "C:\Users\The Dominator\Anaconda3\lib\site-packages\notebook\services\config\handlers.py", line 19, in get
self.finish(json.dumps(self.config_manager.get(section_name)))
File "C:\Users\The Dominator\Anaconda3\lib\site-packages\notebook\services\config\manager.py", line 25, in get
recursive_update(config, cm.get(section_name))
File "C:\Users\The Dominator\Anaconda3\lib\site-packages\notebook\config_manager.py", line 103, in get
recursive_update(data, json.load(f))
File "C:\Users\The Dominator\Anaconda3\lib\json\__init__.py", line 296, in load
parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
File "C:\Users\The Dominator\Anaconda3\lib\json\__init__.py", line 348, in loads
return _default_decoder.decode(s)
File "C:\Users\The Dominator\Anaconda3\lib\json\decoder.py", line 337, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "C:\Users\The Dominator\Anaconda3\lib\json\decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[W 16:53:09.088 NotebookApp] Unhandled error
[E 16:53:09.089 NotebookApp] {
"Host": "localhost:8888",
"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:64.0) Gecko/20100101 Firefox/64.0",
"Accept": "application/json, text/javascript, */*; q=0.01",
"Accept-Language": "en-US,en;q=0.5",
"Accept-Encoding": "gzip, deflate",
"Referer": "http://localhost:8888/notebooks/Untitled9.ipynb?kernel_name=python3",
"X-Xsrftoken": "2|75a37b78|cc87d0162df4fb2b1b60f315193bd447|1546946039",
"X-Requested-With": "XMLHttpRequest",
"Dnt": "1",
"Connection": "keep-alive",
"Cookie": "username-localhost-8889=\"2|1:0|10:1547651085|23:username-localhost-8889|44:NGYzYWNmZTAwYWYxNDA0YjhiMWRhNDNkYzIwN2JhMGU=|18baba9629b1fdb5d25de916d8f9747eeea595d7987d2e390240c2e09f6e4c3c\"; _xsrf=2|75a37b78|cc87d0162df4fb2b1b60f315193bd447|1546946039; username-localhost-8890=\"2|1:0|10:1547652060|23:username-localhost-8890|44:ZmIwYmUzZjM4ZjQ1NDVjMDkzOWU0ZWU1MzBmNWIzNzg=|be75de97adb3af6206a8a59863e71d267434bc2bec5257df296798b0426bd731\"; username-localhost-8888=\"2|1:0|10:1547653983|23:username-localhost-8888|44:NTdlODBlOGMxMWFmNDE0MGE2YmU0Mzg1YjQ4ZDhlZGI=|51413caca4af860f9f0cd3429a26fe95d1e49d7f2af0ba97d62ed991abef3968\""
}
[E 16:53:09.089 NotebookApp] 500 GET /api/config/notebook?_=1547653988936 (::1) 45.88ms referer=http://localhost:8888/notebooks/Untitled9.ipynb?kernel_name=python3
[I 16:53:09.294 NotebookApp] Kernel started: 9e6cb426-f549-427a-8b12-59a303a94e9a
[I 16:53:10.062 NotebookApp] Adapting to protocol v5.1 for kernel 9e6cb426-f549-427a-8b12-59a303a94e9a

**Comment by jasongrout** [comment]
(basically, the error indicates that some config file is no longer JSON, so we're looking to see what is wrong with those files...)

**Comment by norrisan** [comment]
Hi, 

And thanks so much for the prompt and helpful reply

![image](https://user-images.githubusercontent.com/40805460/51309013-c31b7b80-1a43-11e9-870d-1ca01b18b827.png)

![image](https://user-images.githubusercontent.com/40805460/51309075-e6462b00-1a43-11e9-9ae6-2174dcfc3208.png)


![image](https://user-images.githubusercontent.com/40805460/51309190-25747c00-1a44-11e9-9a49-68ea80098dba.png)


So Anaconda 3 doesnt exist as an environment any more. 

Hmm. Seems like a mess, any ideas on the best way to proceed.

**Comment by norrisan** [comment]
> 
> 
> (basically, the error indicates that some config file is no longer JSON, so we're looking to see what is wrong with those files...)

Hi jason, just wondering if you can offer any suggestions?

**Comment by jasongrout** [comment]
> Seems like a mess, any ideas on the best way to proceed.

Agreed. Another thing to do to try to understand exactly what config files are being loaded is to do `jupyter notebook --debug`. That will start out with a lot of debug messages about loading configuration. It may help to see exactly what config files it is finding and trying to access, then to open those and make sure they are valid JSON files (e.g., not empty files). If you do find a file that is empty, perhaps just delete it?

**Comment by norrisan** [comment]
Thank you again so much
This is what i got,

(base) C:\Users\The Dominator>jupyter notebook --debug
[D 14:39:55.293 NotebookApp] Searching ['C:\\Users\\The Dominator',
'C:\\Users\\The Dominator\\.jupyter', 'C:\\Users\\The
Dominator\\Anaconda3\\etc\\jupyter', 'C:\\ProgramData\\jupyter'] for config
files
[D 14:39:55.293 NotebookApp] Looking for jupyter_config in
C:\ProgramData\jupyter
[D 14:39:55.293 NotebookApp] Looking for jupyter_config in C:\Users\The
Dominator\Anaconda3\etc\jupyter
[D 14:39:55.293 NotebookApp] Looking for jupyter_config in C:\Users\The
Dominator\.jupyter
[D 14:39:55.293 NotebookApp] Looking for jupyter_config in C:\Users\The
Dominator
[D 14:39:55.293 NotebookApp] Looking for jupyter_notebook_config in
C:\ProgramData\jupyter
[D 14:39:55.293 NotebookApp] Looking for jupyter_notebook_config in
C:\Users\The Dominator\Anaconda3\etc\jupyter
[D 14:39:55.293 NotebookApp] Loaded config file: C:\Users\The
Dominator\Anaconda3\etc\jupyter\jupyter_notebook_config.json
[D 14:39:55.293 NotebookApp] Looking for jupyter_notebook_config in
C:\Users\The Dominator\.jupyter
[D 14:39:55.293 NotebookApp] Looking for jupyter_notebook_config in
C:\Users\The Dominator
[I 14:39:55.507 NotebookApp] The port 8888 is already in use, trying
another port.
[I 14:39:55.507 NotebookApp] The port 8889 is already in use, trying
another port.
[D 14:39:55.517 NotebookApp] Paths used for configuration of
jupyter_notebook_config:
        C:\ProgramData\jupyter\jupyter_notebook_config.json
[D 14:39:55.517 NotebookApp] Paths used for configuration of
jupyter_notebook_config:
        C:\Users\The
Dominator\Anaconda3\etc\jupyter\jupyter_notebook_config.d\jupyterlab.json
        C:\Users\The
Dominator\Anaconda3\etc\jupyter\jupyter_notebook_config.json
[D 14:39:55.519 NotebookApp] Paths used for configuration of
jupyter_notebook_config:
        C:\Users\The Dominator\.jupyter\jupyter_notebook_config.json
[I 14:39:55.545 NotebookApp] JupyterLab extension loaded from C:\Users\The
Dominator\Anaconda3\lib\site-packages\jupyterlab
[I 14:39:55.545 NotebookApp] JupyterLab application directory is
C:\Users\The Dominator\Anaconda3\share\jupyter\lab
[I 14:39:55.547 NotebookApp] Serving notebooks from local directory:
C:\Users\The Dominator
[I 14:39:55.547 NotebookApp] The Jupyter Notebook is running at:
[I 14:39:55.547 NotebookApp]
http://localhost:8890/?token=bc9a209714d7ac52fa95c0e43f3100017a8b0a65e997664c
[I 14:39:55.547 NotebookApp] Use Control-C to stop this server and shut
down all kernels (twice to skip confirmation).
[C 14:39:55.590 NotebookApp]

    To access the notebook, open this file in a browser:

file:///C:/Users/The%20Dominator/AppData/Roaming/jupyter/runtime/nbserver-7276-open.html
    Or copy and paste one of these URLs:

http://localhost:8890/?token=bc9a209714d7ac52fa95c0e43f3100017a8b0a65e997664c
[D 14:39:56.811 NotebookApp] Accepting token-authenticated connection from
::1
[D 14:39:56.811 NotebookApp] Using contents: services/contents
[D 14:39:56.839 NotebookApp] Path base/images/favicon.ico served from
C:\Users\The
Dominator\Anaconda3\lib\site-packages\notebook\static\base\images\favicon.ico
[D 14:39:56.839 NotebookApp] Path
components/jquery-ui/themes/smoothness/jquery-ui.min.css served from
C:\Users\The
Dominator\Anaconda3\lib\site-packages\notebook\static\components\jquery-ui\themes\smoothness\jquery-ui.min.css
[D 14:39:56.839 NotebookApp] Path
components/jquery-typeahead/dist/jquery.typeahead.min.css served from
C:\Users\The
Dominator\Anaconda3\lib\site-packages\notebook\static\components\jquery-typeahead\dist\jquery.typeahead.min.css
[D 14:39:56.839 NotebookApp] Path style/style.min.css served from
C:\Users\The
Dominator\Anaconda3\lib\site-packages\notebook\static\style\style.min.css
[D 14:39:56.850 NotebookApp] Path components/es6-promise/promise.min.js
served from C:\Users\The
Dominator\Anaconda3\lib\site-packages\notebook\static\components\es6-promise\promise.min.js
[D 14:39:56.850 NotebookApp] Path components/preact/index.js served from
C:\Users\The
Dominator\Anaconda3\lib\site-packages\notebook\static\components\preact\index.js
[D 14:39:56.850 NotebookApp] Path components/proptypes/index.js served from
C:\Users\The
Dominator\Anaconda3\lib\site-packages\notebook\static\components\proptypes\index.js
[D 14:39:56.850 NotebookApp] Path components/preact-compat/index.js served
from C:\Users\The
Dominator\Anaconda3\lib\site-packages\notebook\static\components\preact-compat\index.js
[D 14:39:56.850 NotebookApp] Path components/requirejs/require.js served
from C:\Users\The
Dominator\Anaconda3\lib\site-packages\notebook\static\components\requirejs\require.js
[D 14:39:56.850 NotebookApp] Path base/images/logo.png served from
C:\Users\The
Dominator\Anaconda3\lib\site-packages\notebook\static\base\images\logo.png
[D 14:39:56.850 NotebookApp] Path tree/js/main.min.js served from
C:\Users\The
Dominator\Anaconda3\lib\site-packages\notebook\static\tree\js\main.min.js
[D 14:39:56.850 NotebookApp] 200 GET
/tree?token=bc9a209714d7ac52fa95c0e43f3100017a8b0a65e997664c (::1) 46.69ms
[D 14:39:56.890 NotebookApp] Path custom.css served from C:\Users\The
Dominator\Anaconda3\lib\site-packages\notebook\static\custom\custom.css
[D 14:39:56.890 NotebookApp] 304 GET /custom/custom.css (::1) 0.92ms
[D 14:39:56.900 NotebookApp] Path base\images\logo.png served from
C:\Users\The
Dominator\Anaconda3\lib\site-packages\notebook\static\base\images\logo.png
[D 14:39:56.900 NotebookApp] 200 GET
/static/base/images/logo.png?v=641991992878ee24c6f3826e81054a0f (::1) 0.00ms
[D 14:39:56.910 NotebookApp] Path tree\js\main.min.js served from
C:\Users\The
Dominator\Anaconda3\lib\site-packages\notebook\static\tree\js\main.min.js
[D 14:39:56.920 NotebookApp] 200 GET
/static/tree/js/main.min.js?v=4d7a31cf0e74d526755ed78898e084f9 (::1) 9.95ms
[D 14:39:56.990 NotebookApp] Path base\images\favicon.ico served from
C:\Users\The
Dominator\Anaconda3\lib\site-packages\notebook\static\base\images\favicon.ico
[D 14:39:57.001 NotebookApp] 200 GET
/static/base/images/favicon.ico?v=97c6417ed01bdc0ae3ef32ae4894fd03 (::1)
10.35ms
[D 14:39:57.010 NotebookApp] Path services\contents.js served from
C:\Users\The
Dominator\Anaconda3\lib\site-packages\notebook\static\services\contents.js
[D 14:39:57.010 NotebookApp] 200 GET
/static/services/contents.js?v=20190222143955 (::1) 6.67ms
[D 14:39:57.070 NotebookApp] Paths used for configuration of tree:
        C:\ProgramData\jupyter\nbconfig\tree.json
[D 14:39:57.070 NotebookApp] Paths used for configuration of tree:
        C:\Users\The Dominator\Anaconda3\etc\jupyter\nbconfig\tree.json
[D 14:39:57.080 NotebookApp] Paths used for configuration of tree:
        C:\Users\The Dominator\.jupyter\nbconfig\tree.json
[D 14:39:57.080 NotebookApp] 200 GET /api/config/tree?_=1550842796979 (::1)
9.95ms
[D 14:39:57.080 NotebookApp] Paths used for configuration of common:
        C:\ProgramData\jupyter\nbconfig\common.json
[D 14:39:57.080 NotebookApp] Paths used for configuration of common:
        C:\Users\The Dominator\Anaconda3\etc\jupyter\nbconfig\common.json
[D 14:39:57.080 NotebookApp] Paths used for configuration of common:
        C:\Users\The Dominator\.jupyter\nbconfig\common.json
[D 14:39:57.091 NotebookApp] 200 GET /api/config/common?_=1550842796980
(::1) 10.25ms
[D 14:39:57.100 NotebookApp] Found kernel python3 in C:\Users\The
Dominator\Anaconda3\share\jupyter\kernels
[D 14:39:57.100 NotebookApp] 200 GET /api/kernelspecs (::1) 6.07ms
[D 14:39:57.111 NotebookApp] 200 GET /api/sessions?_=1550842796982 (::1)
10.43ms
[D 14:39:57.120 NotebookApp] 200 GET /api/terminals?_=1550842796983 (::1)
9.89ms
[D 14:39:57.130 NotebookApp] Path custom.js served from C:\Users\The
Dominator\Anaconda3\lib\site-packages\notebook\static\custom\custom.js
[D 14:39:57.133 NotebookApp] 200 GET /custom/custom.js?v=20190222143955
(::1) 12.42ms
[D 14:39:57.164 NotebookApp] 200 GET
/api/contents?type=directory&_=1550842796984 (::1) 30.91ms
[D 14:39:57.170 NotebookApp] 200 GET /api/terminals?_=1550842796981 (::1)
0.00ms
[D 14:39:57.180 NotebookApp] Path
components\font-awesome\fonts\fontawesome-webfont.woff2 served from
C:\Users\The
Dominator\Anaconda3\lib\site-packages\notebook\static\components\font-awesome\fonts\fontawesome-webfont.woff2
[D 14:39:57.180 NotebookApp] 200 GET
/static/components/font-awesome/fonts/fontawesome-webfont.woff2?v=4.7.0
(::1) 0.00ms
[D 14:40:09.922 NotebookApp] 200 GET /api/sessions?_=1550842796985 (::1)
0.00ms
[D 14:40:09.934 NotebookApp] 200 GET /api/terminals?_=1550842796986 (::1)
3.01ms
[D 14:40:09.960 NotebookApp] 200 GET
/api/contents?type=directory&_=1550842796987 (::1) 19.75ms


Is it possible to just delete python and anaconda completely and restart
but keep all the notebooks?

I haven't really a clue what to do and how to find the config files etc.

Thanks for any help.

Andrew
