### ISSUE TITLE
I got Error displaying widget

### ISSUE THREAD

**Issue by xilunaJumma** [jupyter-widgets/ipywidgets#2506]
I got Error displaying widget.

Version Info such as:
jupyter labextension list
JupyterLab **v0.33.12**
Known labextensions:
   app dir: /usr/local/share/jupyter/lab
@jupyter-widgets/jupyterlab-manager
        @jupyter-widgets/jupyterlab-manager **v0.36.2**  enabled  OK
jupyter-matplotlib
        jupyter-matplotlib **v0.4.2**  enabled  OK

My Code such as :
%matplotlib widget
import matplotlib.pyplot as plt
import numpy as np
plt.figure(1)
plt.plot(np.sin(np.linspace(0, 20, 100)))
plt.show()

return: Error displaying widget

from ipywidgets import Text
Text("hello")

also return:Error displaying widget

Could you help me to resolve it ?

**Comment by xilunaJumma** [comment]
And Also my console show this line:
[W 01:53:14.605 LabApp] Got events for closed stream None

**Comment by xilunaJumma** [comment]
![image](https://user-images.githubusercontent.com/27922947/61350573-96cda400-a89a-11e9-84b0-50bb73b19615.png)

**Comment by xilunaJumma** [comment]
![image](https://user-images.githubusercontent.com/27922947/61350629-ce3c5080-a89a-11e9-9ad2-ea73a54a67b6.png)

**Comment by flekschas** [comment]
Same issue with JupyterLab `v1.1.1` and ipywidgets `v7.5.1`. In the webdev console I am seeing

```manager-base.js:273 Could not instantiate widget
(anonymous) @ manager-base.js:273
step @ manager-base.js:44
(anonymous) @ manager-base.js:25
rejected @ manager-base.js:17
Promise.then (async)
step @ manager-base.js:18
(anonymous) @ manager-base.js:19
push.hs2k.__awaiter @ manager-base.js:15
push.hs2k.ManagerBase._make_model @ manager-base.js:257
(anonymous) @ manager-base.js:246
step @ manager-base.js:44
(anonymous) @ manager-base.js:25
(anonymous) @ manager-base.js:19
push.hs2k.__awaiter @ manager-base.js:15
push.hs2k.ManagerBase.new_model @ manager-base.js:232
push.hs2k.ManagerBase.handle_comm_open @ manager-base.js:144
WidgetManager._handleCommOpen @ manager.js:59
_handleCommOpen @ default.js:995
async function (async)
_handleCommOpen @ default.js:994
_handleMessage @ default.js:1101
async function (async)
_handleMessage @ default.js:1067
(anonymous) @ default.js:122
Promise.then (async)
DefaultKernel._onWSMessage @ default.js:119
utils.js:119 Error: Could not create a model.
    at promiseRejection (utils.js:119)
    at async WidgetManager._handleCommOpen (manager.js:59)
    at async DefaultKernel._handleCommOpen (default.js:995)
    at async DefaultKernel._handleMessage (default.js:1101)
promiseRejection @ utils.js:119
Promise.catch (async)
push.hs2k.ManagerBase.handle_comm_open @ manager-base.js:149
WidgetManager._handleCommOpen @ manager.js:59
_handleCommOpen @ default.js:995
async function (async)
_handleCommOpen @ default.js:994
_handleMessage @ default.js:1101
async function (async)
_handleMessage @ default.js:1067
(anonymous) @ default.js:122
Promise.then (async)
DefaultKernel._onWSMessage @ default.js:119
default.js:1001 Exception opening new comm
_handleCommOpen @ default.js:1001
async function (async)
_handleCommOpen @ default.js:994
_handleMessage @ default.js:1101
async function (async)
_handleMessage @ default.js:1067
(anonymous) @ default.js:122
Promise.then (async)
DefaultKernel._onWSMessage @ default.js:119
default.js:127 ChunkLoadError: Loading chunk vendors~@jupyter-widgets/controls failed.
(error: http://localhost:8888/nullnbextensions/higlass-jupyter/vendors~@jupyter-widgets/controls.c2a364e44285e23fe6fa.js)
    at Function.requireEnsure [as e] (http://localhost:8888/static/lab/main.764dabc5398528a1d8da.js:127:26)
    at http://localhost:8888/static/lab/vendors~main.3835e8bd50117adbfc39.js:331010:37
    at new Promise (<anonymous>)
    at exports (http://localhost:8888/static/lab/vendors~main.3835e8bd50117adbfc39.js:331009:20)
    at WidgetManager.loadClass (http://localhost:8888/static/lab/vendors~main.3835e8bd50117adbfc39.js:219061:28)
    at WidgetManager.<anonymous> (http://localhost:8888/static/lab/vendors~main.3835e8bd50117adbfc39.js:262479:46)
    at step (http://localhost:8888/static/lab/vendors~main.3835e8bd50117adbfc39.js:262260:23)
    at Object.next (http://localhost:8888/static/lab/vendors~main.3835e8bd50117adbfc39.js:262241:53)
    at http://localhost:8888/static/lab/vendors~main.3835e8bd50117adbfc39.js:262235:71
    at new Promise (<anonymous>)```

**Comment by jasongrout** [comment]
Can you try a clean install? It seems that there is some installation issue here.

**Comment by pbugnion** [comment]
Closing this for now. Feel free to re-open if you're still having issues.
