### ISSUE TITLE
`import ipywidgets` fails under -OO

### ISSUE THREAD

**Issue by mattpap** [jupyter-widgets/ipywidgets#2524]
This can be reproduced on `master` with:
```
$ python -OO -c "import ipywidgets; print(ipywidgets.__version__)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "ipywidgets/ipywidgets/__init__.py", line 25, in <module>
    from .widgets import *
  File "ipywidgets/ipywidgets/widgets/__init__.py", line 13, in <module>
    from .widget_box import Box, HBox, VBox, GridBox
  File "ipywidgets/ipywidgets/widgets/widget_box.py", line 33, in <module>
    class Box(DOMWidget, CoreWidget):
  File "ipywidgets/ipywidgets/widgets/docutils.py", line 11, in decorator
    cls.__doc__ = cls.__doc__.format(**stripped_snippets)
AttributeError: 'NoneType' object has no attribute 'format'
```
After adding a check for `None` in `ipywidgets.widgets.docutils`, the correct behavior is restored:
```
$ python -OO -c "import ipywidgets; print(ipywidgets.__version__)"
7.5.1
```

**Comment by jasongrout** [comment]
Looks like `-OO` discards docstrings:

```
-OO    : do -O changes and also discard docstrings; add .opt-2 before
         .pyc extension
```
So apparently we should not assume the `__doc__` attribute exists.

**Comment by jasongrout** [comment]
> After adding a check for `None` in `ipywidgets.widgets.docutils`, the correct behavior is restored:

Can you submit a PR?

**Comment by mattpap** [comment]
@jasongrout, see PR #2525.
