### ISSUE TITLE
Widget won't show in jupyter - not found in registry and common fix doesn't work.

### ISSUE THREAD

**Issue by bjornasm** [jupyter-widgets/ipywidgets#2569]
Hi, I am running a jupyter notebook on a windows computer.

```
from ipywidgets import interact
 
def my_function(x):
    return x
interact(my_function, x=20)
```

gives
```

20
<function __main__.my_function(x)>
```

When inspecting in js console I get lots of errors revolving around:

`Could not open comm  --  Error: Class jupyter.widget not found in registry `

When trying a fix I found elsewhere:

`!jupyter nbextension enable --py widgetsnbextension`

I get:

```
Enabling notebook extension jupyter-js-widgets/extension...
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\Scripts\jupyter-nbextension-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_core\application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "C:\ProgramData\Anaconda3\lib\site-packages\notebook\nbextensions.py", line 988, in start
    super(NBExtensionApp, self).start()
  File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_core\application.py", line 255, in start
    self.subapp.start()
  File "C:\ProgramData\Anaconda3\lib\site-packages\notebook\nbextensions.py", line 896, in start
    self.toggle_nbextension_python(self.extra_args[0])
  File "C:\ProgramData\Anaconda3\lib\site-packages\notebook\nbextensions.py", line 872, in toggle_nbextension_python
    logger=self.log)
  File "C:\ProgramData\Anaconda3\lib\site-packages\notebook\nbextensions.py", line 483, in enable_nbextension_python
    logger=logger)
  File "C:\ProgramData\Anaconda3\lib\site-packages\notebook\nbextensions.py", line 386, in _set_nbextension_state_python
    for nbext in nbexts]
  File "C:\ProgramData\Anaconda3\lib\site-packages\notebook\nbextensions.py", line 386, in <listcomp>
    for nbext in nbexts]
  File "C:\ProgramData\Anaconda3\lib\site-packages\notebook\nbextensions.py", line 351, in _set_nbextension_state
    cm.update(section, {"load_extensions": {require: state}})
  File "C:\ProgramData\Anaconda3\lib\site-packages\notebook\config_manager.py", line 134, in update
    data = self.get(section_name)
  File "C:\ProgramData\Anaconda3\lib\site-packages\notebook\config_manager.py", line 103, in get
    recursive_update(data, json.load(f))
  File "C:\ProgramData\Anaconda3\lib\json\__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "C:\ProgramData\Anaconda3\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\ProgramData\Anaconda3\lib\json\decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 8 column 1 (char 72)
```

##Versions:

npm 6.10.2
node v12.8.1
jupyter 4.4.0
ipywidgets 7.5.1

**Comment by jasongrout** [comment]
Looks like your Jupyter notebook config file is not valid JSON. Can you do `jupyter --paths` and look in the config directories listed for an nbconfig directory, and inside that a notebook.json file? My guess is that the notebook.json file is corrupted and actually is not valid json.

**Comment by Harpreet1999** [comment]
Hey I'm having the exact same issue. though the error for 
```
jupyter nbextension enable --py widgetsnbextension
```
ws there for me too but I solved it be deleting the notebook.json file in .jupyter/nbconfig folder


(tardis) harpreet@harpreet-All-Series:~$ jupyter --paths
config:
    /home/harpreet/.jupyter
    /home/harpreet/anaconda3/envs/tardis/etc/jupyter
    /usr/local/etc/jupyter
    /etc/jupyter
data:
    /home/harpreet/.local/share/jupyter
    /home/harpreet/anaconda3/envs/tardis/share/jupyter
    /usr/local/share/jupyter
    /usr/share/jupyter
runtime:
    /home/harpreet/.local/share/jupyter/runtime
