### ISSUE TITLE
Read the docs CI build is quite erratic

### ISSUE THREAD

**Issue by pbugnion** [jupyter-widgets/ipywidgets#2768]
A few weeks ago, we turned on an RTD feature that builds on each PR. The hope was that having CI checks would lead to less broken documentation.

We addressed broken documentation by pointing to stable, rather than latest, so this is less relevant.

Separately, our RTD build fails regularly for various reasons:
- #2754 
- it's currently failing with this error that I can't reproduce locally:

```
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/ipywidgets/envs/2679/lib/python3.7/site-packages/nbsphinx.py", line 891, in parse
    rststring, resources = exporter.from_notebook_node(nb, resources)
  File "/home/docs/checkouts/readthedocs.org/user_builds/ipywidgets/envs/2679/lib/python3.7/site-packages/nbsphinx.py", line 783, in from_notebook_node
    nb, resources = pp.preprocess(nb, resources)
  File "/home/docs/checkouts/readthedocs.org/user_builds/ipywidgets/envs/2679/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 405, in preprocess
    nb, resources = super(ExecutePreprocessor, self).preprocess(nb, resources)
  File "/home/docs/checkouts/readthedocs.org/user_builds/ipywidgets/envs/2679/lib/python3.7/site-packages/nbconvert/preprocessors/base.py", line 69, in preprocess
    nb.cells[index], resources = self.preprocess_cell(cell, resources, index)
  File "/home/docs/checkouts/readthedocs.org/user_builds/ipywidgets/envs/2679/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 448, in preprocess_cell
    raise CellExecutionError.from_cell_and_msg(cell, out)
nbconvert.preprocessors.execute.CellExecutionError: An error occurred while executing the following cell:
------------------
file = open("images/WidgetArch.png", "rb")
image = file.read()
widgets.Image(
    value=image,
    format='png',
    width=300,
    height=400,
)
```

- it's failing on #2765 with yet another error message

I'm not sure if it's our build process that's dubious or RTD that doesn't provide a stable environment, but this is currently slowing down development (I find myself re-triggering builds just to make RTD pass).

I propose removing the webhook. We still have a doc test on Github actions that tests the docs can be built. This seems much more versatile.

**Comment by jasongrout** [comment]
It was nice being able to look at the built docs on a PR to check the doc changes, but I agree that the failing build has been frustrating. I'm fine with removing the webhook until we can get a more reliable build.

**Comment by pbugnion** [comment]
Thanks. I've deleted the webhook and tested a new [PR](https://github.com/jupyter-widgets/ipywidgets/pull/2772) to check the RTD build wasn't dispatched.

I presume existing pull requests will need an extra commit to make the cross go away.
