### ISSUE TITLE
Can't install or update @jupyter-widgets/jupyterlab-manager

### ISSUE THREAD

**Issue by danielfleischer** [jupyter-widgets/ipywidgets#2869]
I get:

```sh 
/ jupyter labextension install @jupyter-widgets/jupyterlab-manager
An error occured.
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf0 in position 23: ordinal not in range(128)
See the log file for details:  /tmp/jupyterlab-debug-zo2ojoaa.log
```

The error log is:
```
Node v14.1.0

Yarn configuration loaded.
> /home/linuxbrew/.linuxbrew/bin/npm pack @jupyter-widgets/jupyterlab-manager
Traceback (most recent call last):

  File "/home/ec2-user/.local/lib/python3.6/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

  File "/home/ec2-user/.local/lib/python3.6/site-packages/jupyterlab/labextensions.py", line 93, in start
    ans = self.run_task()

  File "/home/ec2-user/.local/lib/python3.6/site-packages/jupyterlab/labextensions.py", line 149, in run_task
    for i, arg in enumerate(self.extra_args)

  File "/home/ec2-user/.local/lib/python3.6/site-packages/jupyterlab/labextensions.py", line 149, in <listcomp>
    for i, arg in enumerate(self.extra_args)

  File "/home/ec2-user/.local/lib/python3.6/site-packages/jupyterlab/commands.py", line 388, in install_extension
    return handler.install_extension(extension, pin=pin)

  File "/home/ec2-user/.local/lib/python3.6/site-packages/jupyterlab/commands.py", line 603, in install_extension
    info = self._install_extension(extension, tempdir, pin=pin)

  File "/home/ec2-user/.local/lib/python3.6/site-packages/jupyterlab/commands.py", line 1499, in _install_extension
    info = self._extract_package(extension, tempdir, pin=pin)

  File "/home/ec2-user/.local/lib/python3.6/site-packages/jupyterlab/commands.py", line 1575, in _extract_package
    ret = self._run([which('npm'), 'pack', source], cwd=tempdir)

  File "/home/ec2-user/.local/lib/python3.6/site-packages/jupyterlab/commands.py", line 1752, in _run
    return proc.wait()

  File "/home/ec2-user/.local/lib/python3.6/site-packages/jupyterlab/commands.py", line 107, in wait
    out, _ = proc.communicate(timeout=.1)

  File "/usr/lib64/python3.6/subprocess.py", line 863, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)

  File "/usr/lib64/python3.6/subprocess.py", line 1574, in _communicate
    self.stdout.errors)

  File "/usr/lib64/python3.6/subprocess.py", line 760, in _translate_newlines
    data = data.decode(encoding, errors)

UnicodeDecodeError: 'ascii' codec can't decode byte 0xf0 in position 23: ordinal not in range(128)

Exiting application: jupyter
```

Versions:
widgetsnbextension       3.5.1
jupyterlab               2.1.2
jupyter                  1.0.0
ipykernel                5.2.1
ipywidgets               7.5.1
ipython                  7.14.0
python                3.6.10

**Comment by jasongrout** [comment]
What does the error log say? `/tmp/jupyterlab-debug-zo2ojoaa.log`

**Comment by danielfleischer** [comment]
I edited the message and added the log file.

**Comment by vidartf** [comment]
I think someone else reported a similar issue on the lab repo. If I remember correctly, the solution was to [configure npm to not use unicode characters](https://docs.npmjs.com/using-npm/config#unicode) if your shell (or whatever is handling the piping of output between subprocesses) cannot handle it: `npm set unicode false`

**Comment by danielfleischer** [comment]
Thank you, that fixed the problem. 

On the same machine, using python 3.7 there wasn't an issue as well so I don't understand how setting this `npm` feature fixed the issue. 

Thanks anyway!
