### ISSUE TITLE
Cannot install @jupyter-widgets/jupyterlab-manager, is not a valid npm package

### ISSUE THREAD

**Issue by matthewfranglen** [jupyter-widgets/ipywidgets#2943]
I am trying to install the jupyterlab-manager to enable the plotly widget. When I run:

```
jupyter labextension install @jupyter-widgets/jupyterlab-manager@2
```

I get the error message:

```
An error occured.
ValueError: "@jupyter-widgets/jupyterlab-manager@2" is not a valid npm package
See the log file for details:  /tmp/jupyterlab-debug-y1lqp0fi.log
```

The log file is:

```
Node v12.18.3

Yarn configuration loaded.                                                                                                                                                   
> /usr/local/bin/npm pack @jupyter-widgets/jupyterlab-manager@2
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@jupyter-widgets%2fjupyterlab-manager - Not found                                                                    
npm ERR! 404                                
npm ERR! 404  '@jupyter-widgets/jupyterlab-manager@2' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)                                                                                             
npm ERR! 404                                
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.                                                                                                                          
                                                        
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/matthew/.npm/_logs/2020-08-06T09_29_03_708Z-debug.log                                                                                                     
                                                               
Traceback (most recent call last):
                                                                                                                                                                             
  File "/home/matthew/.local/share/virtualenvs/ds_hashtag_segmentation-CB9Ok_Gb/lib/python3.7/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield
                                                                                                                                                                             
  File "/home/matthew/.local/share/virtualenvs/ds_hashtag_segmentation-CB9Ok_Gb/lib/python3.7/site-packages/jupyterlab/labextensions.py", line 93, in start
    ans = self.run_task()
                                                                              
  File "/home/matthew/.local/share/virtualenvs/ds_hashtag_segmentation-CB9Ok_Gb/lib/python3.7/site-packages/jupyterlab/labextensions.py", line 149, in run_task
    for i, arg in enumerate(self.extra_args)
                                                                                                                                                                             
  File "/home/matthew/.local/share/virtualenvs/ds_hashtag_segmentation-CB9Ok_Gb/lib/python3.7/site-packages/jupyterlab/labextensions.py", line 149, in <listcomp>
    for i, arg in enumerate(self.extra_args)

  File "/home/matthew/.local/share/virtualenvs/ds_hashtag_segmentation-CB9Ok_Gb/lib/python3.7/site-packages/jupyterlab/commands.py", line 388, in install_extension
    return handler.install_extension(extension, pin=pin)

  File "/home/matthew/.local/share/virtualenvs/ds_hashtag_segmentation-CB9Ok_Gb/lib/python3.7/site-packages/jupyterlab/commands.py", line 603, in install_extension
    info = self._install_extension(extension, tempdir, pin=pin)

  File "/home/matthew/.local/share/virtualenvs/ds_hashtag_segmentation-CB9Ok_Gb/lib/python3.7/site-packages/jupyterlab/commands.py", line 1499, in _install_extension
    info = self._extract_package(extension, tempdir, pin=pin)

  File "/home/matthew/.local/share/virtualenvs/ds_hashtag_segmentation-CB9Ok_Gb/lib/python3.7/site-packages/jupyterlab/commands.py", line 1578, in _extract_package
    raise ValueError(msg % source)

ValueError: "@jupyter-widgets/jupyterlab-manager@2" is not a valid npm package

Exiting application: jupyter
```

I've upgraded npm and node. I have cleared the cache.

npm version 6.14.6
node version v12.18.3
jupyter core     : 4.6.3
jupyter-notebook : 6.1.0
qtconsole        : not installed
ipython          : 7.17.0
ipykernel        : 5.3.4
jupyter client   : 6.1.6
jupyter lab      : 2.2.2
nbconvert        : 5.6.1
ipywidgets       : 7.5.1
nbformat         : 5.0.7
traitlets        : 4.3.3

**Comment by vnijs** [comment]
Same ...

**Comment by cjw85** [comment]
Me three when trying to build the scipy container from https://github.com/jupyter/docker-stacks

**Comment by matthewfranglen** [comment]
There may've been a problem with npm itself: https://status.npmjs.org/incidents/cksjqc1w11v5

> The ongoing issue may also affect installation of scoped packages. We continue investigating these issues.
Posted 1 hour ago. Aug 06, 2020 - 08:55 UTC

**Comment by matthewfranglen** [comment]
They are claiming that it is resolved however I am still unable to install the jupyterlab-manager

**Comment by matthewfranglen** [comment]
They have updated the status to resolved:
> The incident has been resolved and we see no errors with installing packages anymore.
> Posted 1 minute ago. Aug 06, 2020 - 12:01 UTC
I am able to install the jupyterlab-manager without issue. I did not have to clear the cache.
