### ISSUE TITLE
RuntimeError: JupyterLab failed to build See the log file for details:  /tmp/jupyterlab-debug-elzuf6lm.log

### ISSUE THREAD

**Issue by Dolphinzzx** [jupyter-widgets/ipywidgets#2977]
When i run "sudo jupyter labextension install @jupyter-widgets/jupyterlab-manager." 

It will prompt following connect.
Building jupyterlab assets (build:prod) 
An error occured. 
RuntimeError: JupyterLab failed to build 
See the log file for details:  /tmp/jupyterlab-debug-elzuf6lm.log
![image](https://user-images.githubusercontent.com/31792429/93876685-d2b79100-fd09-11ea-8eb7-07e3a9ddbabb.png)

System: 
![image](https://user-images.githubusercontent.com/31792429/93876707-da773580-fd09-11ea-8242-8f00c9684b30.png)

Jupyter version:
![image](https://user-images.githubusercontent.com/31792429/93876762-eebb3280-fd09-11ea-8500-c27c46798298.png)

Does anyone know a solution for this?
Thanks advance.

**Comment by manuvazquez** [comment]
Did you get to solve this? I'm having the same issue... When I check the log I see a bunch of stuff that looks OK and then
```
> node /mnt/ntfs_ssd/anaconda3/envs/fastbook/lib/python3.9/site-packages/jupyterlab/staging/yarn.js yarn-deduplicate -s fewer --fail
yarn run v1.21.1
$ /mnt/ntfs_ssd/anaconda3/envs/fastbook/share/jupyter/lab/staging/node_modules/.bin/yarn-deduplicate -s fewer --fail
Done in 0.61s.

> node /mnt/ntfs_ssd/anaconda3/envs/fastbook/lib/python3.9/site-packages/jupyterlab/staging/yarn.js run build:prod:minimize
yarn run v1.21.1
$ ensure-max-old-space webpack --config webpack.prod.minimize.config.js
/mnt/ntfs_ssd/anaconda3/envs/fastbook/share/jupyter/lab/staging/node_modules/webpack-cli/bin/cli.js:93
				throw err;
				^

Error: Cannot find module '@jupyter-widgets/jupyterlab-manager/package.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.resolve (/mnt/ntfs_ssd/anaconda3/envs/fastbook/share/jupyter/lab/staging/node_modules/v8-compile-cache/v8-compile-cache.js:166:23)
    at packageNames.forEach.name (/mnt/ntfs_ssd/anaconda3/envs/fastbook/share/jupyter/lab/staging/node_modules/@jupyterlab/buildutils/lib/build.js:39:45)
    at Array.forEach (<anonymous>)
    at Object.ensureAssets (/mnt/ntfs_ssd/anaconda3/envs/fastbook/share/jupyter/lab/staging/node_modules/@jupyterlab/buildutils/lib/build.js:38:22)
    at Object.<anonymous> (/mnt/ntfs_ssd/anaconda3/envs/fastbook/share/jupyter/lab/staging/webpack.config.js:52:27)
    at Module._compile (/mnt/ntfs_ssd/anaconda3/envs/fastbook/share/jupyter/lab/staging/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (/mnt/ntfs_ssd/anaconda3/envs/fastbook/share/jupyter/lab/staging/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/mnt/ntfs_ssd/anaconda3/envs/fastbook/share/jupyter/lab/staging/webpack.prod.minimize.config.js:4:16)
    at Module._compile (/mnt/ntfs_ssd/anaconda3/envs/fastbook/share/jupyter/lab/staging/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (/mnt/ntfs_ssd/anaconda3/envs/fastbook/share/jupyter/lab/staging/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at WEBPACK_OPTIONS (/mnt/ntfs_ssd/anaconda3/envs/fastbook/share/jupyter/lab/staging/node_modules/webpack-cli/bin/utils/convert-argv.js:114:13)
    at requireConfig (/mnt/ntfs_ssd/anaconda3/envs/fastbook/share/jupyter/lab/staging/node_modules/webpack-cli/bin/utils/convert-argv.js:116:6)
    at /mnt/ntfs_ssd/anaconda3/envs/fastbook/share/jupyter/lab/staging/node_modules/webpack-cli/bin/utils/convert-argv.js:123:17
    at Array.forEach (<anonymous>)
    at module.exports (/mnt/ntfs_ssd/anaconda3/envs/fastbook/share/jupyter/lab/staging/node_modules/webpack-cli/bin/utils/convert-argv.js:121:15)
    at yargs.parse (/mnt/ntfs_ssd/anaconda3/envs/fastbook/share/jupyter/lab/staging/node_modules/webpack-cli/bin/cli.js:71:45)
    at Object.parse (/mnt/ntfs_ssd/anaconda3/envs/fastbook/share/jupyter/lab/staging/node_modules/yargs/yargs.js:576:18)
    at /mnt/ntfs_ssd/anaconda3/envs/fastbook/share/jupyter/lab/staging/node_modules/webpack-cli/bin/cli.js:49:8
    at Object.<anonymous> (/mnt/ntfs_ssd/anaconda3/envs/fastbook/share/jupyter/lab/staging/node_modules/webpack-cli/bin/cli.js:366:3)
child_process.js:632
    throw err;
    ^

Error: Command failed: /mnt/ntfs_ssd/anaconda3/envs/fastbook/share/jupyter/lab/staging/node_modules/.bin/webpack --config webpack.prod.minimize.config.js
    at checkExecSyncError (child_process.js:611:11)
    at Object.execFileSync (child_process.js:629:13)
    at Object.<anonymous> (/mnt/ntfs_ssd/anaconda3/envs/fastbook/share/jupyter/lab/staging/node_modules/@jupyterlab/buildutils/lib/ensure-max-old-space.js:38:17)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

JupyterLab failed to build
Traceback (most recent call last):

  File "/mnt/ntfs_ssd/anaconda3/envs/fastbook/lib/python3.9/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

  File "/mnt/ntfs_ssd/anaconda3/envs/fastbook/lib/python3.9/site-packages/jupyterlab/labextensions.py", line 104, in start
    build(clean_staging=self.should_clean,

  File "/mnt/ntfs_ssd/anaconda3/envs/fastbook/lib/python3.9/site-packages/jupyterlab/commands.py", line 459, in build
    return handler.build(name=name, version=version, static_url=static_url,

  File "/mnt/ntfs_ssd/anaconda3/envs/fastbook/lib/python3.9/site-packages/jupyterlab/commands.py", line 661, in build
    raise RuntimeError(msg)

RuntimeError: JupyterLab failed to build

Exiting application: jupyter
```

**Comment by manuvazquez** [comment]
I figured it out: deleting directory `.cache/yarn` (in Linux) did the trick

**Comment by jtpio** [comment]
Closing as answered by @manuvazquez, thanks!

> I figured it out: deleting directory `.cache/yarn` (in Linux) did the trick

Also worth noting: with JupyterLab 3.0 installing `ipywidgets=7.6` will automatically enable support for widgets in JupyterLab without requiring Node.js to be installed and a new build!
