### ISSUE TITLE
JupyterLab failed to build.

### ISSUE THREAD

**Issue by muriloasouza** [jupyter-widgets/ipywidgets#3410]
Trying to install the labextension in Jupyter Lab 2.3.1.

`jupyter labextension install @jupyter-widgets/jupyterlab-manager`

And getting:

```
Building jupyterlab assets (build:prod:minimize)
An error occured.
RuntimeError: JupyterLab failed to build
```

Here is the log:

```
Node v17.4.0

Yarn configuration loaded.
> C:\Users\Muril\miniconda3\envs\tf-keras-gpu\npm.CMD pack @jupyter-widgets/jupyterlab-manager
npm notice 
npm notice package: @jupyter-widgets/jupyterlab-manager@3.0.1
npm notice === Tarball Contents === 
npm notice 14.5kB LICENSE             
npm notice 2.8kB  README.md           
npm notice 277B   lib/index.d.ts      
npm notice 380B   lib/index.js        
npm notice 5.9kB  lib/manager.d.ts    
npm notice 15.3kB lib/manager.js      
npm notice 1.9kB  lib/output.d.ts     
npm notice 5.3kB  lib/output.js       
npm notice 828B   lib/plugin.d.ts     
npm notice 7.9kB  lib/plugin.js       
npm notice 960B   lib/renderer.d.ts   
npm notice 3.3kB  lib/renderer.js     
npm notice 216B   lib/semvercache.d.ts
npm notice 862B   lib/semvercache.js  
npm notice 3.3kB  package.json        
npm notice 375B   schema/plugin.json  
npm notice === Tarball Details === 
npm notice name:          @jupyter-widgets/jupyterlab-manager          
npm notice version:       3.0.1                                        
npm notice filename:      @jupyter-widgets/jupyterlab-manager-3.0.1.tgz
npm notice package size:  15.6 kB                                      
npm notice unpacked size: 64.0 kB                                      
npm notice shasum:        ba70c14282fb8bd3c6560588f4c7b90b2b2b05fb     
npm notice integrity:     sha512-yhmakhiAFtKtZ[...]RptG4BvNdS+HA==     
npm notice total files:   16                                           
npm notice 
jupyter-widgets-jupyterlab-manager-3.0.1.tgz

Fetching URL: https://registry.yarnpkg.com/@jupyter-widgets%2Fjupyterlab-manager
> C:\Users\Muril\miniconda3\envs\tf-keras-gpu\npm.CMD pack @jupyter-widgets/jupyterlab-manager@2.0.0
npm notice 
npm notice package: @jupyter-widgets/jupyterlab-manager@2.0.0
npm notice === Tarball Contents === 
npm notice 1.5kB  LICENSE             
npm notice 2.1kB  README.md           
npm notice 277B   lib/index.d.ts      
npm notice 380B   lib/index.js        
npm notice 6.0kB  lib/manager.d.ts    
npm notice 15.3kB lib/manager.js      
npm notice 1.9kB  lib/output.d.ts     
npm notice 5.3kB  lib/output.js       
npm notice 828B   lib/plugin.d.ts     
npm notice 7.8kB  lib/plugin.js       
npm notice 960B   lib/renderer.d.ts   
npm notice 3.3kB  lib/renderer.js     
npm notice 216B   lib/semvercache.d.ts
npm notice 862B   lib/semvercache.js  
npm notice 2.3kB  package.json        
npm notice 375B   schema/plugin.json  
npm notice === Tarball Details === 
npm notice name:          @jupyter-widgets/jupyterlab-manager          
npm notice version:       2.0.0                                        
npm notice filename:      @jupyter-widgets/jupyterlab-manager-2.0.0.tgz
npm notice package size:  13.3 kB                                      
npm notice unpacked size: 49.4 kB                                      
npm notice shasum:        05ab402833df07aac1ec2c549a1d748b3c303185     
npm notice integrity:     sha512-i+qtbEe//W9Ru[...]Fu0KbkxM9aQXQ==     
npm notice total files:   16                                           
npm notice 
jupyter-widgets-jupyterlab-manager-2.0.0.tgz

Fetching URL: https://registry.yarnpkg.com/@jupyter-widgets%2Fjupyterlab-manager
> C:\Users\Muril\miniconda3\envs\tf-keras-gpu\npm.CMD pack @jupyter-widgets/jupyterlab-manager@2.0.0
npm notice 
npm notice package: @jupyter-widgets/jupyterlab-manager@2.0.0
npm notice === Tarball Contents === 
npm notice 1.5kB  LICENSE             
npm notice 2.1kB  README.md           
npm notice 277B   lib/index.d.ts      
npm notice 380B   lib/index.js        
npm notice 6.0kB  lib/manager.d.ts    
npm notice 15.3kB lib/manager.js      
npm notice 1.9kB  lib/output.d.ts     
npm notice 5.3kB  lib/output.js       
npm notice 828B   lib/plugin.d.ts     
npm notice 7.8kB  lib/plugin.js       
npm notice 960B   lib/renderer.d.ts   
npm notice 3.3kB  lib/renderer.js     
npm notice 216B   lib/semvercache.d.ts
npm notice 862B   lib/semvercache.js  
npm notice 2.3kB  package.json        
npm notice 375B   schema/plugin.json  
npm notice === Tarball Details === 
npm notice name:          @jupyter-widgets/jupyterlab-manager          
npm notice version:       2.0.0                                        
npm notice filename:      @jupyter-widgets/jupyterlab-manager-2.0.0.tgz
npm notice package size:  13.3 kB                                      
npm notice unpacked size: 49.4 kB                                      
npm notice shasum:        05ab402833df07aac1ec2c549a1d748b3c303185     
npm notice integrity:     sha512-i+qtbEe//W9Ru[...]Fu0KbkxM9aQXQ==     
npm notice total files:   16                                           
npm notice 
jupyter-widgets-jupyterlab-manager-2.0.0.tgz

Incompatible extension:
@jupyter-widgets/jupyterlab-manager
Found compatible version: 2.0.0
> C:\Users\Muril\miniconda3\envs\tf-keras-gpu\npm.CMD pack @jupyter-widgets/jupyterlab-manager@2.0.0
npm notice 
npm notice package: @jupyter-widgets/jupyterlab-manager@2.0.0
npm notice === Tarball Contents === 
npm notice 1.5kB  LICENSE             
npm notice 2.1kB  README.md           
npm notice 277B   lib/index.d.ts      
npm notice 380B   lib/index.js        
npm notice 6.0kB  lib/manager.d.ts    
npm notice 15.3kB lib/manager.js      
npm notice 1.9kB  lib/output.d.ts     
npm notice 5.3kB  lib/output.js       
npm notice 828B   lib/plugin.d.ts     
npm notice 7.8kB  lib/plugin.js       
npm notice 960B   lib/renderer.d.ts   
npm notice 3.3kB  lib/renderer.js     
npm notice 216B   lib/semvercache.d.ts
npm notice 862B   lib/semvercache.js  
npm notice 2.3kB  package.json        
npm notice 375B   schema/plugin.json  
npm notice === Tarball Details === 
npm notice name:          @jupyter-widgets/jupyterlab-manager          
npm notice version:       2.0.0                                        
npm notice filename:      @jupyter-widgets/jupyterlab-manager-2.0.0.tgz
npm notice package size:  13.3 kB                                      
npm notice unpacked size: 49.4 kB                                      
npm notice shasum:        05ab402833df07aac1ec2c549a1d748b3c303185     
npm notice integrity:     sha512-i+qtbEe//W9Ru[...]Fu0KbkxM9aQXQ==     
npm notice total files:   16                                           
npm notice 
jupyter-widgets-jupyterlab-manager-2.0.0.tgz

Node v17.4.0

Yarn configuration loaded.
Building jupyterlab assets (build:prod:minimize)
> node C:\Users\Muril\miniconda3\envs\tf-keras-gpu\lib\site-packages\jupyterlab\staging\yarn.js install --non-interactive
yarn install v1.21.1
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
Done in 0.40s.

> node C:\Users\Muril\miniconda3\envs\tf-keras-gpu\lib\site-packages\jupyterlab\staging\yarn.js yarn-deduplicate -s fewer --fail
yarn run v1.21.1
$ C:\Users\Muril\miniconda3\envs\tf-keras-gpu\share\jupyter\lab\staging\node_modules\.bin\yarn-deduplicate -s fewer --fail
Done in 0.29s.

> node C:\Users\Muril\miniconda3\envs\tf-keras-gpu\lib\site-packages\jupyterlab\staging\yarn.js run build:prod:minimize
yarn run v1.21.1
$ ensure-max-old-space webpack --config webpack.prod.minimize.config.js
node:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:135:10)
    at module.exports (C:\Users\Muril\miniconda3\envs\tf-keras-gpu\share\jupyter\lab\staging\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\Users\Muril\miniconda3\envs\tf-keras-gpu\share\jupyter\lab\staging\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (C:\Users\Muril\miniconda3\envs\tf-keras-gpu\share\jupyter\lab\staging\node_modules\webpack\lib\NormalModule.js:471:10)
    at C:\Users\Muril\miniconda3\envs\tf-keras-gpu\share\jupyter\lab\staging\node_modules\webpack\lib\NormalModule.js:503:5
    at C:\Users\Muril\miniconda3\envs\tf-keras-gpu\share\jupyter\lab\staging\node_modules\webpack\lib\NormalModule.js:358:12
    at C:\Users\Muril\miniconda3\envs\tf-keras-gpu\share\jupyter\lab\staging\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (C:\Users\Muril\miniconda3\envs\tf-keras-gpu\share\jupyter\lab\staging\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at Array.<anonymous> (C:\Users\Muril\miniconda3\envs\tf-keras-gpu\share\jupyter\lab\staging\node_modules\loader-runner\lib\LoaderRunner.js:205:4)
    at Storage.finished (C:\Users\Muril\miniconda3\envs\tf-keras-gpu\share\jupyter\lab\staging\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:55:16)
    at C:\Users\Muril\miniconda3\envs\tf-keras-gpu\share\jupyter\lab\staging\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:91:9
    at C:\Users\Muril\miniconda3\envs\tf-keras-gpu\share\jupyter\lab\staging\node_modules\graceful-fs\graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v17.4.0
node:child_process:869
    throw err;
    ^

Error: Command failed: C:\Users\Muril\miniconda3\envs\tf-keras-gpu\share\jupyter\lab\staging\node_modules\.bin\webpack.CMD --config webpack.prod.minimize.config.js
    at checkExecSyncError (node:child_process:828:11)
    at Object.execFileSync (node:child_process:866:15)
    at Object.<anonymous> (C:\Users\Muril\miniconda3\envs\tf-keras-gpu\share\jupyter\lab\staging\node_modules\@jupyterlab\buildutils\lib\ensure-max-old-space.js:38:17)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 17696,
  stdout: null,
  stderr: null
}

Node.js v17.4.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

JupyterLab failed to build
Traceback (most recent call last):

  File "C:\Users\Muril\miniconda3\envs\tf-keras-gpu\lib\site-packages\jupyterlab\debuglog.py", line 47, in debug_logging
    yield

  File "C:\Users\Muril\miniconda3\envs\tf-keras-gpu\lib\site-packages\jupyterlab\labextensions.py", line 104, in start
    build(clean_staging=self.should_clean,

  File "C:\Users\Muril\miniconda3\envs\tf-keras-gpu\lib\site-packages\jupyterlab\commands.py", line 460, in build
    return handler.build(name=name, version=version, static_url=static_url,

  File "C:\Users\Muril\miniconda3\envs\tf-keras-gpu\lib\site-packages\jupyterlab\commands.py", line 662, in build
    raise RuntimeError(msg)

RuntimeError: JupyterLab failed to build

Exiting application: jupyter
```

**Comment by jasongrout** [comment]
> Trying to install the labextension in Jupyter Lab 2.3.1.
> 
> `jupyter labextension install @jupyter-widgets/jupyterlab-manager`

You'll need to use the specific version of the extension for jlab 2.x: https://github.com/jupyter-widgets/ipywidgets/tree/master/python/jupyterlab_widgets#version-compatibility

`jupyter labextension install @jupyter-widgets/jupyterlab-manager@2`

Also, you might need to use node 16 or node 14.

**Comment by jasongrout** [comment]
> You'll need to use the specific version of the extension for jlab 2.x: https://github.com/jupyter-widgets/ipywidgets/tree/master/python/jupyterlab_widgets#version-compatibility

From the log, it looks like it might be automatically picking the right version of the extension. So then my suggestion is to use node 14 or 16.

**Comment by muriloasouza** [comment]
16 did the trick, thanks!
