### ISSUE TITLE
Check comm_manager is not None before register_target

### ISSUE THREAD

**Issue by TTianshun** [jupyter-widgets/ipywidgets#3739]
## Description

I've met a similiar error with https://github.com/jupyter-widgets/pythreejs/issues/399
Here's the test code

```python
from IPython.core.magic import cell_magic, magics_class, Magics, needs_local_scope
from IPython.testing.globalipapp import start_ipython

@magics_class
class TestMagics(Magics):

    @needs_local_scope
    @cell_magic
    def celltest(self, line, cell, local_ns) -> None:
        from IPython.display import display
        from ipywidgets import Button
        button = Button(description="celltest")
        display(button)

def load_ipython_extension(ipython) -> None:
    ipython.register_magics(TestMagics)

ip = start_ipython()
load_ipython_extension(ip)
ip.run_cell_magic(magic_name="celltest", line="", cell="print(1)")
```

the output is:
```
Traceback (most recent call last):
  File "/home/pts/ipywidgets/test_issue.py", line 21, in <module>
    ip.run_cell_magic(magic_name="celltest", line="", cell="print(1)")
  File "/home/pts/ipywidgets/venv/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 2430, in run_cell_magic
    result = fn(*args, **kwargs)
  File "/home/pts/ipywidgets/test_issue.py", line 12, in celltest
    from ipywidgets import Button
  File "/home/pts/ipywidgets/venv/lib/python3.8/site-packages/ipywidgets/__init__.py", line 59, in <module>
    _handle_ipython()
  File "/home/pts/ipywidgets/venv/lib/python3.8/site-packages/ipywidgets/__init__.py", line 57, in _handle_ipython
    register_comm_target()
  File "/home/pts/ipywidgets/venv/lib/python3.8/site-packages/ipywidgets/__init__.py", line 47, in register_comm_target
    comm_manager = get_comm_manager()
  File "/home/pts/ipywidgets/venv/lib/python3.8/site-packages/ipywidgets/__init__.py", line 33, in get_comm_manager
    if ip is not None and ip.kernel is not None:
AttributeError: 'TerminalInteractiveShell' object has no attribute 'kernel'
```

I found a pr #3737  that fixes this error,
Then I applied the pr on my code, another error occurred:

```
Traceback (most recent call last):
  File "/home/pts/ipywidgets/test_issue.py", line 21, in <module>
    ip.run_cell_magic(magic_name="celltest", line="", cell="print(1)")
  File "/home/pts/ipywidgets/venv/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 2430, in run_cell_magic
    result = fn(*args, **kwargs)
  File "/home/pts/ipywidgets/test_issue.py", line 12, in celltest
    from ipywidgets import Button
  File "/home/pts/ipywidgets/venv/lib/python3.8/site-packages/ipywidgets/__init__.py", line 59, in <module>
    _handle_ipython()
  File "/home/pts/ipywidgets/venv/lib/python3.8/site-packages/ipywidgets/__init__.py", line 57, in _handle_ipython
    register_comm_target()
  File "/home/pts/ipywidgets/venv/lib/python3.8/site-packages/ipywidgets/__init__.py", line 49, in register_comm_target
    comm_manager.register_target('jupyter.widget', Widget.handle_comm_opened)
AttributeError: 'NoneType' object has no attribute 'register_target'
```

So I think we should check and make sure `comm_manager` is not `None` before `register_target`

## Environment

- python version 3.8.5
- ipywidgets version 8.0.5
- Operating System and version: WSL2 Ubuntu 20.04

**Comment by TTianshun** [comment]
I made a pull request about this issue.
